### ISSUE TITLE
Define Tree interface

### ISSUE THREAD

**Issue by thiagovas** [LBD-UFMG/MachineLearning#6]
The Tree interface will represent the decision tree.

Proposal of properties:
- An object of splitter.
- An object of Criterion.
- The maximum number of features used to create the tree.
- The maximum depth of the tree.
- The maximum number of leaf nodes of the tree.
- The minimum number of samples per leaf.
- The minimum number of samples per node in order to be splitted in two.
- * Class weight.

\* Probably

**Comment by raphaelcampos** [comment]
I got it!

**Comment by gcmgomes** [comment]
I think the items

> - The maximum number of features used to create the tree.
> - The minimum number of features used to create the tree.

Should actually be a feature for the `Sampler` classes. What do you guys think?

**Comment by raphaelcampos** [comment]
The `Sampler` is a more general class, isn't?
It will not only server the trees or Random Forests, but also other classes.

I may have a wrong understanding of `Sampler`. I thought It would be a class (module) similar to what we have in python http://docs.scipy.org/doc/numpy/reference/routines.random.html.

**Comment by gcmgomes** [comment]
We could have `Sampler` serve both for feature and document sampling. Instead of a vector of `document_weight` we would have a vector of `sample_weight`. This way, `Sampler` would just return to us a vector with the ids of the selected objects. Its a bit more troublesome then leaving the `feature_count` members inside the tree interface, but it will let us use the same ideas of  min/max sampling wherever we want.

**Comment by clebsonc** [comment]
Let's think. Since the Sampler is responsible for only passing out the training data to build the trees, it does not make sense to delegate the maximum and minimum number of  features for the sampler class.

So to understand better, when I instantiate a sampler object and request for some underlying data representation to build the tree what in your opinion it should return? A pair of a vector containing the reference to the documents and a vector containing the reference to the features of each document?

I think that it's better if we return only the raw underlying data representation and let the tree take care of how to manage the use of the features.

**Comment by raphaelcampos** [comment]
I agree with both of you. As mentioned, we must have a generic sampler just to deal with random sampling of any array/vector representing, for instance, the id of the documents/features.
Second, max and min features must be tree-specific attributes as mentioned by @clebsonc, because they have to do with tree building procedure.

Let me refresh (difference between min and max features): max features is the total number of features sampled without replacement from the original set of features, which will be evaluated at splitting time. min features is?

**Comment by raphaelcampos** [comment]
Other stuff to be considered, we must have an interface to represent an classifier or regressor (similar scikit's estimator). 

It has methods signatures such as:
- fit(X, y): method to fit the modal
- predict(X): predicts the labels of instances of X based on the fitted model
- predict_proba(X) : returns the predicted probability distribution of all possible classes of each instance in X

It may have others, but those are the only ones I remember now.

Shall we do the same?

**Comment by gcmgomes** [comment]
I agree with the idea of classifier/regressor interface, but let's take it to another issue. The merging of the feature and document `Sampler` is an effort towards a more reusable codebase. I'd say we still need the min/max parameters inside it, but we can do it in another issue.

**Comment by clebsonc** [comment]
Regarding the proposed properties, there is a mistake :D. I was looking at our whiteboard and we did not define the attribute minimum number of features. I think that @thiagovas typed it twice. The features on the whiteboard are only: splitter, criterion, max_features, max_depth, min_samples_leaf, min_samples_split, max_leaf_nodes and class_weight.

Agreed with @gcmgomes that we should take the classifier/regressor to another issue.

**Comment by thiagovas** [comment]
yeah, there isn't a min_features. But I agree that the max_features property should belong to the sampler class. The sampler can decide while retrieving which features from the documents it will return. The tree just have to do the splits. And nothing stops us from receiving max_features on the Tree constructor and just pass it to the sampler.

**Comment by gcmgomes** [comment]
We should avoid this kind of constructor (parameter passing for an inner object) and instead focus on [Dependency Injection](https://en.wikipedia.org/wiki/Dependency_injection). This way our classes only have to worry about using the objects in the correct manner instead of also having to know how to properly build them.

**Comment by raphaelcampos** [comment]
Issue closed by merge #12
